#!/usr/bin/env bash

# Initialize the FILENAME variable
FILENAME=""

# Iterate through the arguments
for arg in "$@"; do
    # Check if the argument is not a flag
    if [[ ${arg:0:2} != "--" ]]; then
        # Set the FILENAME variable and break the loop
        FILENAME="$arg"
        break
    fi
done

# Function to move Python imports to the top
move_imports() {
    local FILENAME="$1"

    # Create a temporary file
    local TMP_FILE=$(mktemp)

    local FIRST_LINE=$(head -n 1 "$FILENAME")
    if [[ $FIRST_LINE == "#%%"* || $FIRST_LINE == "# %%"* ]]; then
        # Remove the first line
        sed -i '1d' "$FILENAME"

        # Prepend the first line at the beginning of the original file
        echo "$FIRST_LINE" >"$TMP_FILE"
    fi

    # Extract lines matching the pattern and store them in a temporary file
    sed -n -e '/^import.*\|^from.*import.*/p' "$FILENAME" >>"$TMP_FILE"

    # Remove the extracted lines from the original file
    sed -i '/^import.*\|^from.*import.*/d' "$FILENAME"

    # Prepend the extracted lines at the beginning of the original file
    cat "$TMP_FILE" "$FILENAME" >temp && mv temp "$FILENAME"
}

# Uncompromising Python code formatter -- Google 2-space style
cblack "$FILENAME" &
sleep 0.1

# Move all imports to the top
move_imports "$FILENAME" &
sleep 0.1

# Sort imports
isort "$FILENAME" &
